### ISSUE TITLE
General question - different NCO implementation

### ISSUE THREAD

**Issue by mryndzionek** [dawsonjon/PicoRX#18]
I've noticed [this](https://github.com/RPiks/pico-hf-oscillator/tree/main) project. Claims to achieve sub-Hz resolution. Would it be beneficial/necessary for this project? Needs one core to be clocked at 270MHz.

**Comment by dawsonjon** [comment]
Yes, sub Hz (or arbitrarily fine) resolution is possible. I use this technique in the transmitter project https://101-things.readthedocs.io/en/latest/ham_transmitter.html. The downside is that it needs a fair bit of CPU. I was able to make a fairly efficient solution that works without overclocking the CPU using DMA, about 10% of the CPU on one core is used to generate the NCO and a further 10% is needed for the modulation. 

At the moment, I still favour using the PIO clock divider in the receiver because it is much simpler to implement and doesn't use any CPU. I don't think that there would be much benefit to further reducing the bandwidth of the QSD, it is actually beneficial to have a small frequency offset to avoid low frequency noise around DC.

**Comment by mryndzionek** [comment]
Thanks!
